export type Wilderness =
  | 'abandoned village'
  | 'ancient guardians'
  | 'ancient monument'
  | 'bandit lair'
  | 'beast nests'
  | 'broken infrastructure'
  | 'chokepoint'
  | 'criminal meet'
  | 'cryptic art'
  | 'decayed enchantment'
  | 'disused mine'
  | 'enchanted wreckage'
  | 'healing terrain'
  | 'hermitage'
  | 'hostile stronghold'
  | 'isolated academy'
  | 'labyrinthine tangle'
  | 'lost battlefield'
  | 'lost city'
  | 'magical springs'
  | 'migration path'
  | 'military outpost'
  | 'monstrous beast'
  | 'motherlode'
  | 'nomad camp'
  | 'oceanic travel'
  | 'overgrown tomb'
  | 'perilous path'
  | 'pilgrimage site'
  | 'precious game'
  | 'rampant experiment'
  | 'refugee camp'
  | 'remnant road'
  | 'remote monastery'
  | 'ruined fortification'
  | 'savage hamlet'
  | 'sculpted terrain'
  | 'seductive peril'
  | 'taboo territory'
  | 'tainted wilderness'
  | 'toxic ruins'
  | 'treacherous terrain'
  | 'twisted fauna'
  | 'uncanny weather'
  | 'wilder tribe'
  | 'vicious flora'
  | 'zealot colony'
