export type primordial__use_trait_tags =
  | 'wood products'
  | 'firewood'
  | 'edible'
  | 'textiles'
  | 'elixirs'
  | 'poisons'
  | 'drugs'
  | 'inks'
  | 'enchantments'
  | 'explosives'
  | 'adhesives'
  | 'perfumes'
  | 'decorative'
  | 'ceremonial'
  | 'root bridges'
  | 'faction control'
