import { Trait } from '../../utilities/traits/types'

export type ProvinceHook =
  | 'abandoned structures'
  | 'abandoned village'
  | 'ancestral seat'
  | 'ancient archives'
  | 'ancient forge'
  | 'ancient monument'
  | 'artisan guilds'
  | 'artistic patrons'
  | 'assassins guild'
  | 'automaton guardians'
  | 'bad water'
  | 'bandit camp'
  | 'black market'
  | 'blood feud'
  | 'buried ruins'
  | 'canal streets'
  | 'caravan routes'
  | 'contested ruins'
  | 'contested shipwreck'
  | 'corrupt officials'
  | 'corrupted elemental'
  | 'criminal syndicate'
  | 'crop failure'
  | 'crop theft'
  | 'crumbling ruins'
  | 'cryptic art'
  | 'crystalline horrors'
  | 'cursed artifact'
  | 'cursed local'
  | 'cyclical doom'
  | 'dangerous wildlife'
  | 'dark cult'
  | 'defiled land'
  | 'degenerate cannibals'
  | 'desecrated shrine'
  | 'despotic lord'
  | 'dire tombs'
  | 'disappearing caravans'
  | 'distant gate'
  | 'distressed noble'
  | 'dueling explorers'
  | 'dying forest'
  | 'ethnic tensions'
  | 'experimental lab'
  | 'feral magic'
  | 'flooded halls'
  | 'food shortage'
  | 'forbidden faith'
  | 'forced evictions'
  | 'foreign spies'
  | 'forgotten mines'
  | 'fortress monastery'
  | 'fungal garden'
  | 'fungal infestation'
  | 'gang warfare'
  | 'ghost ship'
  | 'grand library'
  | 'harsh occupation'
  | 'haunted estate'
  | 'hazardous district'
  | 'heretical beliefs'
  | 'hivemind natives'
  | 'hostile terrain'
  | 'incompetent leaders'
  | 'invading army'
  | 'isolated academy'
  | 'knightly order'
  | 'lawless chaos'
  | 'lethal treasure'
  | 'limited access'
  | 'living dungeon'
  | 'lost battlefield'
  | 'magical academy'
  | 'malignant slums'
  | 'marriage alliance'
  | 'massacre site'
  | 'master artisan'
  | 'mercenary companies'
  | 'merchant council'
  | 'migration path'
  | 'military outpost'
  | 'missing hunters'
  | 'missionary zeal'
  | 'monster forge'
  | 'monstrous tribute'
  | 'natural disaster'
  | 'necromantic cult'
  | 'neglectful ruler'
  | 'new industry'
  | 'noble intrigue'
  | 'nomadic traders'
  | 'old lighthouse'
  | 'opulent court'
  | 'oracle bones'
  | 'petrified garden'
  | 'pilgrimage site'
  | 'pirate haven'
  | 'pirate scourge'
  | 'plague outbreak'
  | 'plundered tribute'
  | 'poacher problems'
  | 'prophetic halls'
  | 'prosperous land'
  | 'punishment post'
  | 'rare reagents'
  | 'rebel stronghold'
  | 'recent brutality'
  | 'reclusive hermit'
  | 'reformist struggle'
  | 'refugee camps'
  | 'remnant faith'
  | 'remote monastery'
  | 'renegade sorcerer'
  | 'revanchist exile'
  | 'ritual preparation'
  | 'riverine escort'
  | 'ruined castle'
  | 'sacred grove'
  | 'sacred harvest'
  | 'sacred hunt'
  | 'sealed evil'
  | 'sectarian violence'
  | 'sinking city'
  | 'slave markets'
  | 'slave uprising'
  | 'sleeping guardian'
  | 'sorcerous cabal'
  | 'stolen artifact'
  | 'syncretic faith'
  | 'taboo wardens'
  | 'temple cults'
  | 'terrible beast'
  | 'toxic economy'
  | 'toxic miasma'
  | 'tribal migration'
  | 'underground arena'
  | 'underground sewers'
  | 'unique product'
  | 'vampiric clan'
  | 'wanted outlaw'
  | 'war conscripts'
  | 'witch coven'
  | 'witch hunts'
  | 'wizards lair'
  | 'xenophobic locals'
  | "coup d'etat"
  | "elder's disappearance"
  | "river's wrath"
  | "spirit's blessing"

export type ProvinceHooks = Record<
  ProvinceHook,
  Trait<
    ProvinceHook,
    {
      urban?: boolean
      coastal?: boolean
      warfare?: boolean
      rivers?: boolean
      tribal?: boolean
    }
  >
>
