export type beast__behavior_trait_tags =
  | 'territorial'
  | 'vocalization'
  | 'heat_tolerant'
  | 'cold_tolerant'
  | 'scarcity'
  | 'mutualistic'
  | 'commensalistic'
  | 'echolocation'
  | 'navigation'
  | 'hemophage'
  | 'infestation'
  | 'scavenger'
  | 'detritivore'
  | 'ancient'
