const _professions = [
  // lower
  'peasant',
  'village elder',
  'clan head',
  'laborer',
  'beggar',
  'servant',
  'sailor',
  'dock worker',
  'actor',
  'singer',
  'poet',
  'artist',
  'musician',
  'courtesan',
  'criminal',
  'tomb robber',
  'bandit warlord',
  'ruins explorer',
  'guard',
  'monster hunter',
  'chef',
  'waiter',
  'bartender',
  'grave keeper',
  'sorcerer (petty)',
  'clergy (petty)',
  'missionary',
  'merchant (petty)',
  'bureaucrat (petty)',
  'coachman',
  'archivist',
  'beastmaster',
  // middle
  'ruler (rural)',
  'gentry',
  'bureaucrat (minor)',
  'bureaucrat (major)',
  'guard captain',
  'bodyguard',
  'templar',
  'criminal (boss, minor)',
  'criminal (boss, major)',
  'stable master',
  'innkeeper',
  'clergy (minor)',
  'clergy (major)',
  'lawyer',
  'scholar',
  'sorcerer (minor)',
  'sorcerer (major)',
  'singer (famous)',
  'poet (famous)',
  'artist (famous)',
  'musician (famous)',
  'courtesan (famous)',
  'baker',
  'butcher',
  'brewer',
  'blacksmith',
  'silversmith',
  'goldsmith',
  'glassblower',
  'jeweler',
  'leatherworker',
  'woodcarver',
  'cobbler',
  'weaver',
  'tailor',
  'herbalist',
  'alchemist',
  'surgeon',
  'artificer',
  'guild master',
  'merchant (minor)',
  'merchant (major)',
  'caravan trader',
  'caravan master',
  'ship captain',
  'dock master',
  'visiting gentry',
  // upper
  'ruler (urban)',
  'sorcerer (great)',
  'clergy (great)',
  'templar (grandmaster)',
  'ethnarch',
  'merchant (prince)',
  'aristocrat (lord)',
  'aristocrat (heir)',
  'diplomat',
  'courtier'
] as const
export type Profession = typeof _professions[number]
export type ProfessionDetails = {
  title?: string | { male: string; female: string }
  strata: 'lower' | 'middle' | 'upper'
  coastal?: boolean
  official?: boolean
  urban?: boolean
  culture?: 'foreign' | 'native'
  age?: 'novice' | 'veteran' | 'master'
  weight?: number
  unique?: boolean
  villain?: boolean
}
