const _professions = [
  // lower
  'peasant',
  'village elder',
  'laborer',
  'beggar',
  'servant',
  'sailor',
  'dock worker',
  'actor',
  'singer',
  'poet',
  'artist',
  'musician',
  'courtesan',
  'criminal',
  'bandit',
  'bandit warlord',
  'ruins explorer',
  'guard',
  'bounty hunter',
  'monster hunter',
  'chef',
  'waiter',
  'bartender',
  'grave keeper',
  'sorcerer (petty)',
  'clergy (petty)',
  'missionary',
  'merchant (petty)',
  'bureaucrat (petty)',
  'coachman',
  'archivist',
  'beastmaster',
  // middle
  'gentry',
  'bureaucrat (minor)',
  'bureaucrat (major)',
  'guard captain',
  'bodyguard',
  'templar',
  'criminal boss',
  'stable master',
  'innkeeper',
  'clergy (minor)',
  'clergy (major)',
  'lawyer',
  'scholar',
  'sorcerer (minor)',
  'sorcerer (major)',
  'singer (famous)',
  'poet (famous)',
  'artist (famous)',
  'musician (famous)',
  'courtesan (famous)',
  'baker',
  'butcher',
  'brewer',
  'blacksmith',
  'silversmith',
  'goldsmith',
  'glassblower',
  'jeweler',
  'leatherworker',
  'woodcarver',
  'cobbler',
  'weaver',
  'tailor',
  'herbalist',
  'alchemist',
  'surgeon',
  'artificer',
  'guild master',
  'merchant (minor)',
  'merchant (major)',
  'caravan trader',
  'caravan master',
  'ship captain (merchant)',
  'ship captain (pirate)',
  'dock master',
  // upper
  'sorcerer (great)',
  'clergy (great)',
  'templar (grandmaster)',
  'ethnarch',
  'merchant (prince)',
  'aristocrat',
  'diplomat',
  'courtier'
] as const
export type Profession = typeof _professions[number]
export type ProfessionDetails = {
  title?: string | { male: string; female: string }
  strata: 'lower' | 'middle' | 'upper'
  coastal?: boolean
  official?: boolean
  urban?: boolean
  culture?: 'foreign' | 'native'
  age?: 'novice' | 'veteran' | 'master'
  weight?: number
  unique?: boolean
  villain?: boolean
}
