export type beast__appearance_trait_tags =
  | 'polymorphic'
  | 'markings'
  | 'contrast'
  | 'aged_coloration'
  | 'arctic_coloration'
  | 'mimicry'
  | 'ornamentation'
  | 'horns'
  | 'nose_horns'
  | 'tusks'
  | 'antlers'
  | 'shell'
  | 'humps'
  | 'bioluminescence'
