export type ReligiousProfessions =
  | 'acolyte'
  | 'monk'
  | 'abbot'
  | 'templar'
  | 'inquisitor'
  | 'missionary'
  | 'priest (petty)'
  | 'priest (minor)'
  | 'priest (major)'
  | 'priest (great)'
