export type ArtistProfessions =
  | 'woodcarver'
  | 'barber'
  | 'artist'
  | 'painter'
  | 'cartographer'
  | 'writer'
  | 'poet'
  | 'calligrapher'
  | 'illuminator'
  | 'potter'
  | 'sculptor'
  | 'tattooer'
  | 'curator'
