export type settlement__conflict =
  | 'blood feud'
  | "coup d'état"
  | 'culled nobility'
  | 'dark secret'
  | 'deadly plague'
  | 'devastation'
  | 'food shortage'
  | 'foreign spies'
  | 'foreign occupation'
  | 'foul sorcery'
  | 'heretical faith'
  | 'imminent invasion'
  | 'natural disaster'
  | 'poacher problems'
  | 'political asylum'
  | 'rebel stronghold'
  | 'reformation edict'
  | 'stolen tribute'
  | 'succession dispute'
  | 'tenuous diplomacy'
  | 'toxic economy'
  | 'wanted outlaw'
  | 'warlord rule'
  | 'witch hunts'
