export type martial_professions =
  | 'soldier (military, recruit)'
  | 'soldier (military, seasoned)'
  | 'officer (military, minor)'
  | 'officer (military, major)'
  | 'general (military)'
  | 'soldier (rebels, recruit)'
  | 'soldier (rebels, seasoned)'
  | 'officer (rebels, minor)'
  | 'officer (rebels, major)'
  | 'general (rebels)'
  | 'militia'
  | 'militia (captain)'
  | 'guard'
  | 'guard (captain)'
  | 'guard (noble)'
  | 'guard (noble, captain)'
  | 'mercenary'
  | 'mercenary (captain)'

export type mercenary_specs = 'defender' | 'brute' | 'marksman' | 'rogue' | 'sorcerer'
export type soldier_specs = 'scout' | 'infantry' | 'cavalry' | 'artillery' | 'sapper'
