export type dungeon__environment =
  | 'abundant traps'
  | 'chokepoint'
  | 'contagion'
  | 'dampened arcana'
  | 'decrepit structure'
  | 'dungeon heart'
  | 'flooding'
  | 'honey traps'
  | 'infestation'
  | 'isolation'
  | 'labyrinthine'
  | 'limited access'
  | 'lingering curse'
  | 'noxious fumes'
  | 'taboo territory'
  | 'temporal distortion'
  | 'wild magic'
