export type Court =
  | "affliction's mark"
  | 'ancestral obligation'
  | 'awesome legitimacy'
  | 'awkward birth'
  | 'blandished leadership'
  | 'capricious orders'
  | 'cultural insignia'
  | 'daring ambition'
  | 'dark secret'
  | 'decadent court'
  | "devil's bargain"
  | 'diplomatic demands'
  | 'disputed inheritance'
  | 'excess heirs'
  | 'false prize'
  | 'fatal extravagance'
  | 'forbidden romance'
  | 'foreign ties'
  | 'gate keeper'
  | 'hopeless rival'
  | 'impure blood'
  | 'inadequate tools'
  | 'inept ruler'
  | 'iron law'
  | 'lost purpose'
  | 'magical subversion'
  | 'ministerial capture'
  | 'new generation'
  | 'new opportunity'
  | 'outside debts'
  | 'overextended grasp'
  | 'poisonous cliques'
  | 'rampant corruption'
  | 'recent brutality'
  | 'priestly influence'
  | 'proxy speaker'
  | 'restive lessers'
  | 'rival dreams'
  | 'rival power'
  | 'shining successor'
  | 'splendid seat'
  | 'ruling regalia'
  | 'runaway rule'
  | 'sublime skill'
  | 'sudden strength'
  | 'threatened violence'
  | 'waning wealth'

export type CourtGroup =
  | 'aristocratic'
  | 'bureaucratic'
  | 'residential'
  | 'mercantile'
  | 'religious'
  | 'criminal'
  | 'royal'
