export type MerchantProfessions =
  | 'caravan (trader)'
  | 'caravan (master)'
  | 'innkeeper'
  | 'tavern keeper'
  | 'merchant (prince)'
  | 'merchant'
  | 'banker'

export type MerchantSpecializations =
  | 'alchemical'
  | 'arcane'
  | 'armor'
  | 'books'
  | 'clothing'
  | 'cosmetics'
  | 'general'
  | 'instruments'
  | 'leather'
  | 'produce'
  | 'religious'
  | 'ships'
  | 'weapons'
