export type government_professions =
  | 'advisor (noble)'
  | 'advisor (state)'
  | 'advocate'
  | 'bureaucrat (city)'
  | 'bureaucrat (town)'
  | 'bureaucrat (village)'
  | 'constable'
  | 'courier'
  | 'diplomat'
  | 'executioner'
  | 'herald'
  | 'interpreter'
  | 'magistrate'
  | 'scribe'
  | 'spy'
  | 'tax collector'
