export type grove__icon =
  | 'grove_1'
  | 'grove_2'
  | 'grove_3'
  | 'grove_4'
  | 'grove_5'
  | 'grove_6'
  | 'grove_7'
  | 'grove_8'
  | 'grove_9'
  | 'grove_10'
  | 'grove_11'
  | 'grove_12'
  | 'grove_13'
  | 'grove_14'
