export type LaborerProfessions =
  | 'beekeeper'
  | 'carpenter'
  | 'embalmer'
  | 'falconer'
  | 'farmer (tenant)'
  | 'farmer (yeoman)'
  | 'fisherman'
  | 'herdsman'
  | 'hound master'
  | 'hunter'
  | 'laborer'
  | 'lumberjack'
  | 'lumberjack (foreman)'
  | 'mason'
  | 'miller (owner)'
  | 'miller'
  | 'miner'
  | 'miner (foreman)'
  | 'stable master'
  | 'stable hand'
  | 'thatcher'
  | 'trapper'
