export type WizardProfessions =
  | 'wizard (petty)'
  | 'wizard (minor)'
  | 'wizard (major)'
  | 'wizard (great)'
  | 'oracle'
  | 'fortune teller'
  | 'druid (petty)'
  | 'druid (minor)'
  | 'druid (major)'
  | 'druid (great)'
