export type underworld_professions =
  | 'thief (minor)'
  | 'assassin (minor)'
  | 'courtesan (minor)'
  | 'thief (major)'
  | 'assassin (major)'
  | 'courtesan (major)'
  | 'forger'
  | 'beggar'
  | 'smuggler'
  | 'fence'
  | 'con artist'
  | 'brigand'
  | 'brigand (chief)'
  | 'boss (criminal, minor)'
  | 'advisor (criminal, minor)'
  | 'boss (criminal, major)'
  | 'advisor (criminal, major)'
