export const missions = {
  defense: {
    text: 'Protect a friend against an impending threat',
    complication: [
      "There's a mole feeding info to the enemy",
      "The target doesn't believe there's a threat",
      'The enemy is actually a different group',
      'Someone close by would prefer they failed',
      'Target has a secret defensive advantage',
      'Enemy wants to frighten, not destroy it',
      'Current defense plans are badly flawed',
      "Expected defenders aren't there",
      'The opposition has unanticipated gear',
      'The PCs could profit greatly by betrayal',
      'A false alarm will happen while guarding',
      'The PCs are actually guarding a decoy',
      'The target resents this and is uncooperative',
      'An “ally” really wants the target gone',
      'The current guardians are incompetent',
      'The target is overconfident in their defenses',
      "They've misunderstood the real target",
      'The assailants are on a strict time limit',
      'They have a lot of active enemies'
    ]
  },
  espionage: {
    text: 'Acquire sensitive information that will benefit a friend',
    complication: [
      'False data was placed as a decoy',
      'The data will actually harm the client',
      'Someone else is stealing the data as well',
      'The data is worthless unless stolen quickly',
      "The data is only in a single person's head",
      'Obtaining the data will hurt an innocent',
      "There's unexpected info in the data",
      'The data is attached to a precious object',
      'An important figure keeps the data near',
      'The data is only accessible at certain times',
      "There's a key needed to decode the data",
      'A copy of the data has been mislaid',
      'The data was stolen and hid by someone',
      'The data is a unique physical object',
      'Stealing it will enrage a third party',
      'Its guardians are focused on a different file',
      "It's really just a pointer to the real data"
    ]
  },
  sabotage: {
    text: 'Destroy a {thing|place} that is important to the enemy',
    complication: [
      "It's currently held or used by a third party",
      "It's only accessible at particular times",
      'An innocent is reliant on its safety',
      'There are hostages kept near by it',
      "It's a very tempting target for thieving PCs",
      "It's spread out over several locations",
      "It's abnormally resilient to damage",
      'The client only wants it lightly damaged',
      'It must be stolen but seemingly destroyed',
      'The site is entangled with a different use',
      'The site is keenly on alert for sabotage',
      'The sabotage must look like mere bad luck',
      "It's already partially damaged or ailing",
      'Guard reinforcements are coming soon',
      'The PCs need inside help to get at it',
      'The target is underground somewhere',
      'Someone just stole or seized the target',
      "It's being used for an unexpected purpose"
    ]
  },
  smuggling: {
    text: 'Transport a thing across a restricted zone',
    complication: [
      "There's another, richer buyer for the goods",
      'A rival wants to bribe the PCs to go astray',
      'The goods are decoys to draw attention',
      'The goods would be useful to the PCs too',
      "It isn't what the recipient expected to get",
      'The transit route changes unexpectedly',
      'Bribed officials have been replaced',
      'Local law enforcement is active there',
      'A government official is involved in things',
      'A gang leader or crime boss wants in on it',
      'Somebody wants the run to fail badly',
      'A sympathetic group needs the goods',
      'The goods have been cut or adulterated',
      'New “taxes” are on the transit route',
      'A local wants a cut of the goods',
      'Another smuggler wants the shipment',
      'The price goes down the longer it takes',
      'The trade must take place in a public area'
    ]
  },
  theft: {
    text: 'Steal a thing from enemy forces',
    complication: [
      "There's a decoy target in place",
      "Someone's seeking to buy it openly",
      "Somebody's inspecting it right now",
      'Somebody dangerous carries it often',
      'Taking it would hurt a sympathetic group',
      'Another group of thieves are aiming at it',
      'The owner has been tipped to the threat',
      'A recent theft attempt failed badly',
      "They've recently changed up security",
      'Fighting near it is likely to damage it',
      "It's physically attached to something",
      'Its owner would rather it wrecked than lost',
      'One of its guardians is amenable to bribes',
      'A third party wants to ensure its safety',
      'It needs to be delivered to a specific site',
      "It's surrounded by valuable objects",
      "It's rather carelessly guarded"
    ]
  },
  rescue: {
    text: 'Retrieve a friend from a dangerous situation',
    complication: [
      'They set up their own kidnapping',
      'They thought this was just a normal job',
      'The patron wants them dead or alive',
      'They have a reason not to want to leave',
      'The captors genuinely need their help',
      'Their captors are ideological allies',
      'Someone else is trying to assassinate them',
      'Ransom was paid, but got stolen',
      "They're kept constantly on the move",
      'They escaped but are now lost somewhere',
      "They'll be killed if not rescued soon",
      "They'll be killed once no longer needed",
      'Their captors are very solicitous to them',
      "They've hidden loot somewhere nearby",
      'They have a friend among their captors',
      'They must be extracted to a specific place',
      'Their location is dangerous to get to',
      "They're injured and largely immobile",
      "They won't leave without a friend there",
      "They've obtained a position of power there"
    ]
  },
  bounty: {
    text: 'Defeat a dangerous enemy',
    complication: [
      'A failed attempt would bring disastrous consequences',
      'It has a swarm of spawn or loyal servitors to guard it',
      'Locals placate the thing with sacrifices and fear its anger',
      "The creature always flees a fight it's not sure it will win",
      'The creature has hostages or prisoners in its lair',
      'The creature is extremely hard to locate or identify',
      "The client's confused about the target",
      'The target is constantly on the move',
      'The target is wanted captured and alive',
      'Someone else is making a hit on them, too',
      'Their guards are not particularly loyal',
      "There's going to be a gap in their guarding",
      'Their death must be hidden for a while',
      "The client's info about them is wrong",
      'They must be killed in a certain way/place'
    ]
  },
  retrieval: {
    text: 'Recover a lost thing',
    complication: [
      'It starts degrading when recovered',
      "It's extremely fragile in some way",
      "It's more valuable than the client thought",
      'Somebody else already has claimed it',
      'The locals where it is have no clue about it',
      "It's been collected as worthless scrap",
      "Somebody's using it in an unexpected way",
      "It's in multiple pieces that must be obtained",
      "It's tangled in some larger device or thing",
      "It's in a hazardous building or area",
      'The client only needs one part from it',
      "It's got a dangerous secret embedded in it",
      'A removable part is very valuable',
      "It's tremendously illegal to possess it",
      "It's government property of some kind",
      "It's among many similar-looking objects",
      "It's hidden inside a living creature",
      'It requires special gear to handle it',
      "It's going to be ruined soon if not retrieved",
      "The thing has a decoy that's actually a trap",
      'The thing is actually totally different from what it seems',
      'The thing moves constantly, so locations go stale rapidly',
      'There are many examples of the thing, all but one fake'
    ]
  },
  explore: {
    text: 'Gather information about a place',
    complication: [
      'A third party offers pay to deceive',
      "The place looks like what it isn't",
      'Existing info about the place is wrong',
      'A third party is keeping people out',
      'The only source of a critical fact is missing',
      'A third party is monitoring the place',
      'The PCs need to find the last scout team',
      "The client's real interest is hidden from PCs",
      'The apparent place is only part of it; most of it is hidden',
      'The locals are terrified that the PCs will stir up trouble',
      'Hazardous flora make up a natural trap for those ignorant of their perils',
      'Numerous deadfalls or covered pits have been placed on side paths here',
      'The area is positioned somewhere that has an excellent view of most approaches to it',
      "There's a nest or lair of some dangerous animal obstructing easy entrance, but the occupants know how to deal with them",
      "The area's inside the hunting territory of some dreadful creature",
      'It extremely well-concealed amid the terrain'
    ]
  }
} as const

export type Mission = keyof typeof missions
