export type TransportProfessions =
  | 'sailor (merchant, novice)'
  | 'sailor (navy, novice)'
  | 'sailor (pirate, novice)'
  | 'sailor (merchant, seasoned)'
  | 'sailor (navy, seasoned)'
  | 'sailor (pirate, seasoned)'
  | 'ferryman'
  | 'dock worker'
  | 'dock master'
  | 'coachman'
  | 'waggoner'
  | 'ship captain (merchant)'
  | 'ship captain (navy)'
  | 'ship captain (pirate)'

export type SailorSpecs = 'cannoneer' | 'navigator' | 'boatswain' | 'helmsman' | 'deckhand'
